Created Output Log File: /workdir/tasks_run/data/logs/data_dictionary_20240911_14h23m55s.csv
====== whole_session_data ======
script_starting_time,2024-09-11 14:23:47.116929
sambashare_dir_path,/workdir/tasks_run/data/sambashare
roi_mask_dir_path,/workdir/tasks_run/data/roi_masks
log_directory_path,/workdir/tasks_run/data/logs
starting_block,1
number_of_trials,140
retries_before_ending,3
output_text_logfile_path,/workdir/tasks_run/data/logs/calculator_script_20240911_14h23m47s.txt
roi_mask_path,/workdir/tasks_run/data/roi_masks/P004_e3_registered_rifg.nii
dicom_dir_path,/workdir/tasks_run/data/sambashare/test_dir
starting_dicoms_in_dir,143
dicoms_in_dir,146
scripting_ending_time,2024-09-11 14:23:55.567557
script_total_time,0:00:08.450630
script_ending_cause,keyboard interrupt
====== block1 ======
block_start_time,2024-09-11 14:23:47.122558
num_trials_failed,0
nii_list,[]
event_dict,{}
resid_list,[]
nf_scores,[]
====== trial1 ======
trial_start_time,2024-09-11 14:23:47.125438
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/95079712560434681997.dcm
errors,"[('time_of_error: 20240911_14h23m51s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 29, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 93, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h23m51s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 29, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 93, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h23m52s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 29, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 93, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_tries,3
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR1.nii
mean_activation,432.0825
successful_trial_end,True
ending_trial_time,2024-09-11 14:23:52.945522
total_trial_time,0:00:05.820089
====== trial2 ======
trial_start_time,2024-09-11 14:23:52.948709
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/95079712560434681997.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR2.nii
mean_activation,432.0825
successful_trial_end,True
ending_trial_time,2024-09-11 14:23:53.025422
total_trial_time,0:00:00.076718
====== trial3 ======
trial_start_time,2024-09-11 14:23:53.028438
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/88246264095033105802.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR3.nii
mean_activation,431.4536
successful_trial_end,True
ending_trial_time,2024-09-11 14:23:53.349558
total_trial_time,0:00:00.321125
====== trial4 ======
trial_start_time,2024-09-11 14:23:53.352656
keyboard_interrupt,2024-09-11 14:23:53.942448
block_end_time,2024-09-11 14:23:55.564563
total_block_time,0:00:08.442008
