Created Output Log File: /workdir/tasks_run/data/logs/data_dictionary_20240911_14h19m16s.csv
====== whole_session_data ======
script_starting_time,2024-09-11 14:18:42.397099
sambashare_dir_path,/workdir/tasks_run/data/sambashare
roi_mask_dir_path,/workdir/tasks_run/data/roi_masks
log_directory_path,/workdir/tasks_run/data/logs
starting_block,1
number_of_trials,140
retries_before_ending,3
output_text_logfile_path,/workdir/tasks_run/data/logs/calculator_script_20240911_14h18m42s.txt
roi_mask_path,/workdir/tasks_run/data/roi_masks/P004_e3_registered_rifg.nii
dicom_dir_path,/workdir/tasks_run/data/sambashare/test_dir
starting_dicoms_in_dir,98
dicoms_in_dir,124
scripting_ending_time,2024-09-11 14:19:16.883417
script_total_time,0:00:34.486322
script_ending_cause,keyboard interrupt
====== block1 ======
block_start_time,2024-09-11 14:18:42.409299
num_trials_failed,0
nii_list,[]
event_dict,{}
resid_list,[]
nf_scores,[]
====== trial1 ======
trial_start_time,2024-09-11 14:18:42.411995
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/95568997936722447225.dcm
errors,"[('time_of_error: 20240911_14h18m47s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h18m47s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h18m47s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,3
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR1.nii
mean_activation,432.0825
successful_trial_end,True
ending_trial_time,2024-09-11 14:18:48.838496
total_trial_time,0:00:06.426506
====== trial2 ======
trial_start_time,2024-09-11 14:18:48.841283
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/95568997936722447225.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR2.nii
mean_activation,432.0825
successful_trial_end,True
ending_trial_time,2024-09-11 14:18:48.920769
total_trial_time,0:00:00.079491
====== trial3 ======
trial_start_time,2024-09-11 14:18:48.923738
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/41222448449631951493.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR3.nii
mean_activation,431.4536
successful_trial_end,True
ending_trial_time,2024-09-11 14:18:49.111571
total_trial_time,0:00:00.187838
====== trial4 ======
trial_start_time,2024-09-11 14:18:49.114477
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/63758674970113196529.dcm
errors,"[('time_of_error: 20240911_14h18m50s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h18m50s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h18m51s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,3
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR4.nii
mean_activation,434.17578
successful_trial_end,True
ending_trial_time,2024-09-11 14:18:51.971823
total_trial_time,0:00:02.857351
====== trial5 ======
trial_start_time,2024-09-11 14:18:51.974870
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/63758674970113196529.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR5.nii
mean_activation,434.17578
successful_trial_end,True
ending_trial_time,2024-09-11 14:18:52.051317
total_trial_time,0:00:00.076451
====== trial6 ======
trial_start_time,2024-09-11 14:18:52.054232
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/99916356749474546649.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR6.nii
mean_activation,431.29163
successful_trial_end,True
ending_trial_time,2024-09-11 14:18:52.361142
total_trial_time,0:00:00.306915
====== trial7 ======
trial_start_time,2024-09-11 14:18:52.364081
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/93390977271340313848.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR7.nii
mean_activation,431.14517
successful_trial_end,True
ending_trial_time,2024-09-11 14:18:53.425331
total_trial_time,0:00:01.061255
====== trial8 ======
trial_start_time,2024-09-11 14:18:53.428410
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/33602845137490159971.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR8.nii
mean_activation,429.82474
successful_trial_end,True
ending_trial_time,2024-09-11 14:18:54.488086
total_trial_time,0:00:01.059681
====== trial9 ======
trial_start_time,2024-09-11 14:18:54.491015
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/2404593089320107334.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR9.nii
mean_activation,432.17102
successful_trial_end,True
ending_trial_time,2024-09-11 14:18:55.548410
total_trial_time,0:00:01.057400
====== trial10 ======
trial_start_time,2024-09-11 14:18:55.551746
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/29477303842717142778.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR10.nii
mean_activation,432.77783
successful_trial_end,True
ending_trial_time,2024-09-11 14:18:56.625569
total_trial_time,0:00:01.073828
====== trial11 ======
trial_start_time,2024-09-11 14:18:56.628781
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/48893003490251891047.dcm
errors,"[('time_of_error: 20240911_14h18m57s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h18m57s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h18m58s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,3
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR11.nii
mean_activation,432.2796
successful_trial_end,True
ending_trial_time,2024-09-11 14:18:59.402279
total_trial_time,0:00:02.773502
====== trial12 ======
trial_start_time,2024-09-11 14:18:59.405452
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/48893003490251891047.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR12.nii
mean_activation,432.2796
successful_trial_end,True
ending_trial_time,2024-09-11 14:18:59.482842
total_trial_time,0:00:00.077394
====== trial13 ======
trial_start_time,2024-09-11 14:18:59.485751
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/47358424490477128350.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR13.nii
mean_activation,429.6359
successful_trial_end,True
ending_trial_time,2024-09-11 14:18:59.796005
total_trial_time,0:00:00.310259
====== trial14 ======
trial_start_time,2024-09-11 14:18:59.799278
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/39504352266643489702.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR14.nii
mean_activation,431.57898
successful_trial_end,True
ending_trial_time,2024-09-11 14:19:00.880512
total_trial_time,0:00:01.081238
====== trial15 ======
trial_start_time,2024-09-11 14:19:00.883412
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/88040503926331079234.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR15.nii
mean_activation,430.9837
successful_trial_end,True
ending_trial_time,2024-09-11 14:19:01.960919
total_trial_time,0:00:01.077511
====== trial16 ======
trial_start_time,2024-09-11 14:19:01.963958
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/93979756773930250541.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR16.nii
mean_activation,432.25427
successful_trial_end,True
ending_trial_time,2024-09-11 14:19:03.049220
total_trial_time,0:00:01.085267
====== trial17 ======
trial_start_time,2024-09-11 14:19:03.052153
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/62851598028873183114.dcm
errors,"[('time_of_error: 20240911_14h19m03s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h19m04s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h19m04s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,3
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR17.nii
mean_activation,431.58627
successful_trial_end,True
ending_trial_time,2024-09-11 14:19:05.714484
total_trial_time,0:00:02.662336
====== trial18 ======
trial_start_time,2024-09-11 14:19:05.717560
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/62851598028873183114.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR18.nii
mean_activation,431.58627
successful_trial_end,True
ending_trial_time,2024-09-11 14:19:05.793535
total_trial_time,0:00:00.075979
====== trial19 ======
trial_start_time,2024-09-11 14:19:05.796644
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/85458598586281045770.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR19.nii
mean_activation,430.89218
successful_trial_end,True
ending_trial_time,2024-09-11 14:19:06.229018
total_trial_time,0:00:00.432378
====== trial20 ======
trial_start_time,2024-09-11 14:19:06.232261
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/56482104671200996097.dcm
errors,"[('time_of_error: 20240911_14h19m07s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h19m07s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h19m08s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,3
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR20.nii
mean_activation,436.00302
successful_trial_end,True
ending_trial_time,2024-09-11 14:19:08.902843
total_trial_time,0:00:02.670587
====== trial21 ======
trial_start_time,2024-09-11 14:19:08.905936
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/56482104671200996097.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR21.nii
mean_activation,436.00302
successful_trial_end,True
ending_trial_time,2024-09-11 14:19:08.983429
total_trial_time,0:00:00.077498
====== trial22 ======
trial_start_time,2024-09-11 14:19:08.986460
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/48443289716751926285.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR22.nii
mean_activation,432.88843
successful_trial_end,True
ending_trial_time,2024-09-11 14:19:09.412182
total_trial_time,0:00:00.425726
====== trial23 ======
trial_start_time,2024-09-11 14:19:09.415317
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/48674284008788585536.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR23.nii
mean_activation,433.4012
successful_trial_end,True
ending_trial_time,2024-09-11 14:19:10.487315
total_trial_time,0:00:01.072003
====== trial24 ======
trial_start_time,2024-09-11 14:19:10.490318
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/24213243426620116728.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR24.nii
mean_activation,430.7673
successful_trial_end,True
ending_trial_time,2024-09-11 14:19:11.554682
total_trial_time,0:00:01.064368
====== trial25 ======
trial_start_time,2024-09-11 14:19:11.557590
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/53625855141122240911.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR25.nii
mean_activation,436.92654
successful_trial_end,True
ending_trial_time,2024-09-11 14:19:12.528840
total_trial_time,0:00:00.971255
====== trial26 ======
trial_start_time,2024-09-11 14:19:12.531753
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/81780480578414679114.dcm
errors,"[('time_of_error: 20240911_14h19m13s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h19m13s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h19m14s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 88, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_retries,2
keyboard_interrupt,2024-09-11 14:19:14.785578
block_end_time,2024-09-11 14:19:16.872773
total_block_time,0:00:34.463477
