Created Output Log File: /workdir/tasks_run/data/logs/data_dictionary_20240911_14h29m16s.csv
====== whole_session_data ======
script_starting_time,2024-09-11 14:28:44.611118
sambashare_dir_path,/workdir/tasks_run/data/sambashare
roi_mask_dir_path,/workdir/tasks_run/data/roi_masks
log_directory_path,/workdir/tasks_run/data/logs
starting_block,1
number_of_trials,140
retries_before_ending,3
output_text_logfile_path,/workdir/tasks_run/data/logs/calculator_script_20240911_14h28m44s.txt
roi_mask_path,/workdir/tasks_run/data/roi_masks/P004_e3_registered_rifg.nii
dicom_dir_path,/workdir/tasks_run/data/sambashare/test_dir
starting_dicoms_in_dir,153
dicoms_in_dir,171
blocks_failed,1
scripting_ending_time,2024-09-11 14:29:16.829977
script_total_time,0:00:32.218862
script_ending_cause,keyboard interrupt
====== block1 ======
block_start_time,2024-09-11 14:28:44.615935
num_trials_failed,3
nii_list,[]
event_dict,{}
resid_list,[]
nf_scores,[]
====== trial1 ======
trial_start_time,2024-09-11 14:28:44.618802
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/21512799827367550794.dcm
errors,"[('time_of_error: 20240911_14h28m56s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h28m56s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h28m56s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h28m56s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_tries,4
successful_trial_end,False
ending_trial_time,2024-09-11 14:28:56.524779
total_trial_time,0:00:11.905980
====== trial2 ======
trial_start_time,2024-09-11 14:28:56.527570
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/50981404741452767957.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR2.nii
mean_activation,432.0825
successful_trial_end,True
ending_trial_time,2024-09-11 14:28:57.603292
total_trial_time,0:00:01.075727
====== trial3 ======
trial_start_time,2024-09-11 14:28:57.606180
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/38785323343249661200.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR3.nii
mean_activation,431.4536
successful_trial_end,True
ending_trial_time,2024-09-11 14:28:58.677866
total_trial_time,0:00:01.071691
====== trial4 ======
trial_start_time,2024-09-11 14:28:58.680812
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/84485279594057955072.dcm
errors,"[('time_of_error: 20240911_14h28m59s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h28m59s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h28m59s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h28m59s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_tries,4
successful_trial_end,False
ending_trial_time,2024-09-11 14:28:59.755584
total_trial_time,0:00:01.074775
====== trial5 ======
trial_start_time,2024-09-11 14:28:59.758390
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/86150617843675294095.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR5.nii
mean_activation,434.17578
successful_trial_end,True
ending_trial_time,2024-09-11 14:29:00.815847
total_trial_time,0:00:01.057461
====== trial6 ======
trial_start_time,2024-09-11 14:29:00.819033
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/66841242271154389355.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR6.nii
mean_activation,431.29163
successful_trial_end,True
ending_trial_time,2024-09-11 14:29:01.887222
total_trial_time,0:00:01.068193
====== trial7 ======
trial_start_time,2024-09-11 14:29:01.890173
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/35344339158468128305.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR7.nii
mean_activation,431.14517
successful_trial_end,True
ending_trial_time,2024-09-11 14:29:02.855597
total_trial_time,0:00:00.965429
====== trial8 ======
trial_start_time,2024-09-11 14:29:02.858527
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/99255965952074566453.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR8.nii
mean_activation,429.82474
successful_trial_end,True
ending_trial_time,2024-09-11 14:29:03.936518
total_trial_time,0:00:01.077996
====== trial9 ======
trial_start_time,2024-09-11 14:29:03.939899
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/96670224132855913058.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR9.nii
mean_activation,432.17102
successful_trial_end,True
ending_trial_time,2024-09-11 14:29:05.037478
total_trial_time,0:00:01.097584
====== trial10 ======
trial_start_time,2024-09-11 14:29:05.040548
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/71876795123290762644.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR10.nii
mean_activation,432.77783
successful_trial_end,True
ending_trial_time,2024-09-11 14:29:06.123046
total_trial_time,0:00:01.082502
====== trial11 ======
trial_start_time,2024-09-11 14:29:06.126267
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/14802214282576430973.dcm
errors,"[('time_of_error: 20240911_14h29m07s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h29m07s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h29m07s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h29m07s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_tries,4
successful_trial_end,False
ending_trial_time,2024-09-11 14:29:07.205590
total_trial_time,0:00:01.079326
block_end_time,2024-09-11 14:29:07.206533
total_block_time,0:00:22.590599
====== block2 ======
block_start_time,2024-09-11 14:29:07.211006
num_trials_failed,1
nii_list,[]
event_dict,{}
resid_list,[]
nf_scores,[]
====== trial1 ======
trial_start_time,2024-09-11 14:29:07.214069
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/50865125265627622315.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR1.nii
mean_activation,432.2796
successful_trial_end,True
ending_trial_time,2024-09-11 14:29:08.273616
total_trial_time,0:00:01.059551
====== trial2 ======
trial_start_time,2024-09-11 14:29:08.276987
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/66251337551780422087.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR2.nii
mean_activation,429.6359
successful_trial_end,True
ending_trial_time,2024-09-11 14:29:09.250838
total_trial_time,0:00:00.973855
====== trial3 ======
trial_start_time,2024-09-11 14:29:09.253996
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/31278673730084110721.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR3.nii
mean_activation,431.57898
successful_trial_end,True
ending_trial_time,2024-09-11 14:29:10.339867
total_trial_time,0:00:01.085875
====== trial4 ======
trial_start_time,2024-09-11 14:29:10.342927
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/66692036496864688304.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR4.nii
mean_activation,430.9837
successful_trial_end,True
ending_trial_time,2024-09-11 14:29:11.409819
total_trial_time,0:00:01.066897
====== trial5 ======
trial_start_time,2024-09-11 14:29:11.412706
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/896481953672488140.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR5.nii
mean_activation,432.25427
successful_trial_end,True
ending_trial_time,2024-09-11 14:29:12.477492
total_trial_time,0:00:01.064791
====== trial6 ======
trial_start_time,2024-09-11 14:29:12.480677
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/29504907608580361687.dcm
errors,"[('time_of_error: 20240911_14h29m13s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h29m13s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h29m13s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h29m13s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 90, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_tries,4
successful_trial_end,False
ending_trial_time,2024-09-11 14:29:13.552390
total_trial_time,0:00:01.071716
====== trial7 ======
trial_start_time,2024-09-11 14:29:13.555238
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/50521471825266788990.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR7.nii
mean_activation,431.58627
successful_trial_end,True
ending_trial_time,2024-09-11 14:29:14.621922
total_trial_time,0:00:01.066688
====== trial8 ======
trial_start_time,2024-09-11 14:29:14.624846
keyboard_interrupt,2024-09-11 14:29:14.969046
block_end_time,2024-09-11 14:29:16.826165
total_block_time,0:00:09.615162
