Created Output Log File: /workdir/tasks_run/data/nfb_logs/p004_data_dictionary_20240911_23h46m56s.csv
====== whole_session_data ======
script_starting_time,2024-09-11 23:46:42.488019
sambashare_dir_path,/workdir/tasks_run/data/sambashare
starting_block,1
retries_before_ending,3
pid,p004
dicom_dir_path,/workdir/tasks_run/data/sambashare/test_dir
output_text_logfile_path,/workdir/tasks_run/data/nfb_logs/p004_calculator_script_20240911_23h46m42s.txt
roi_mask_dir_path,/workdir/tasks_run/data/roi_masks
roi_mask_path,/workdir/tasks_run/data/roi_masks/P004_e3_registered_rifg.nii
log_directory_path,/workdir/tasks_run/data/nfb_logs
number_of_trials,140
starting_dicoms_in_dir,188
dicoms_in_dir,190
scripting_ending_time,2024-09-11 23:46:55.999957
script_total_time,0:00:13.511945
script_ending_cause,keyboard interrupt
====== block1 ======
block_start_time,2024-09-11 23:46:44.118201
num_trials_failed,0
nii_list,[]
event_dict,{}
resid_list,[]
nf_scores,[]
====== trial1 ======
trial_start_time,2024-09-11 23:46:44.121782
this_trial_tries,3
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/88071641823349728863.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR1.nii
errors,"[('time_of_error: 20240911_23h46m50s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 26, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 23, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""mean_activation""] = calculations_MW.get_mean_activation(roi_mask=dictionary[""whole_session_data""][""roi_mask_path""], nifti_image_path=dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""])\n  File ""/workdir/tasks_run/scripts/calculations_MW.py"", line 39, in get_mean_activation\n    log.print_and_log(f""Mean ROI Activation: {mean_activation}"")\n  File ""/workdir/tasks_run/scripts/log.py"", line 70, in print_and_log\n    log_name = file_handler.get_most_recent(action=""txt_output_log"")\nNameError: name \'file_handler\' is not defined\n'), ('time_of_error: 20240911_23h46m51s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 26, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 23, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""mean_activation""] = calculations_MW.get_mean_activation(roi_mask=dictionary[""whole_session_data""][""roi_mask_path""], nifti_image_path=dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""])\n  File ""/workdir/tasks_run/scripts/calculations_MW.py"", line 39, in get_mean_activation\n    log.print_and_log(f""Mean ROI Activation: {mean_activation}"")\n  File ""/workdir/tasks_run/scripts/log.py"", line 70, in print_and_log\n    log_name = file_handler.get_most_recent(action=""txt_output_log"")\nNameError: name \'file_handler\' is not defined\n')]"
failed_dicoms,['/workdir/tasks_run/data/sambashare/test_dir/36288010028664961085.dcm']
keyboard_interrupt,2024-09-11 23:46:52.821710
num_trials_with_errors,2
block_end_time,2024-09-11 23:46:55.993199
total_block_time,0:00:11.875008
